/**
 * Builds a standalone browser harness for the router's behavioural suite.
 *
 * The suite itself lives in `src/selftest.js` and is the single source of truth
 * for both runners. This script only produces the HTML shell that loads those
 * modules in a browser.
 *
 * Each module is embedded base64-encoded and decoded at runtime, so no amount of
 * backticks, `${}` or `</script>` inside the sources can corrupt the page — the
 * usual failure mode when inlining JavaScript by hand.
 *
 * Usage:  node tools/build-harness.mjs
 * Output: test/browser-harness.html
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')
const srcDir = join(root, 'src')
const outFile = join(root, 'test', 'browser-harness.html')

/** Load order matters only for readability; imports are rewritten at runtime. */
const MODULES = ['pool.js', 'health.js', 'router.js', 'selftest.js']

const encoded = Object.fromEntries(
  MODULES.map(file => [file, readFileSync(join(srcDir, file)).toString('base64')]),
)

const payload = JSON.stringify(encoded, null, 2)

const html = `<!doctype html>
<meta charset="utf-8">
<title>dsh-model-auto-router — behavioural verification</title>
<style>
  body { font: 13px/1.55 ui-monospace, Menlo, Consolas, monospace; margin: 16px; }
  .pass { color: #137333; } .fail { color: #b3261e; font-weight: 700; }
  h1 { font-size: 15px; margin: 0 0 10px; }
  #summary { margin: 10px 0; padding: 8px; background: #f4f4f5; font-weight: 700; }
</style>
<body>
<h1>dsh-model-auto-router — behavioural verification</h1>
<div id="summary">running…</div>
<div id="out"></div>
<script type="module">
// Generated by tools/build-harness.mjs — do not edit by hand.
//
// The modules are embedded base64-encoded, decoded here, and turned into blob
// URLs with their relative import specifiers rewritten to each other. The page
// therefore executes the exact files from src/ through the canonical suite in
// src/selftest.js, identical to what \`node --test\` runs.
const ENCODED = ${payload}

const FILES = Object.keys(ENCODED)
const decode = name => new TextDecoder().decode(Uint8Array.from(atob(ENCODED[name]), c => c.charCodeAt(0)))

const urls = {}
for (const file of FILES) {
  let text = decode(file)
  for (const dep of FILES) text = text.split(\`'\${'./' + dep}'\`).join(\`'\${urls[dep]}'\`)
  urls[file] = URL.createObjectURL(new Blob([text], { type: 'text/javascript' }))
}

// The suite imports pool.js, health.js and router.js by their real specifiers.
const suite = await import(urls['selftest.js'])
const { total, passed, failed, results } = suite.runSelfTest()

const out = document.getElementById('out')
for (const result of results) {
  const line = document.createElement('div')
  line.className = result.ok ? 'pass' : 'fail'
  line.textContent = (result.ok ? 'PASS  ' : 'FAIL  ') + result.name + (result.ok ? '' : '  → ' + result.error)
  out.appendChild(line)
}

const summary = document.getElementById('summary')
summary.textContent = \`\${passed}/\${total} passed\` + (failed ? \`  —  \${failed} FAILED\` : '  —  ALL GREEN')
summary.style.color = failed ? '#b3261e' : '#137333'
document.title = failed ? \`FAIL \${failed}\` : 'ALL PASS'
</script>
</body>
`

writeFileSync(outFile, html, 'utf8')
console.log(`wrote ${outFile} (${MODULES.length} modules, ${html.length} bytes)`)
